import { TypographySet, TYPOGRAPHY_SCALES } from '../models/typography';

/**
 * Typography Sets for Presentations
 * 10 carefully crafted combinations of serif and sans-serif fonts
 * All fonts are available via Google Fonts for easy deployment
 */

export const typographySets: TypographySet[] = [
  // 1. Classic Professional - Playfair Display + Inter
  {
    id: 'classic-professional',
    name: 'Classic Professional',
    description: 'Elegant serif headings with clean sans-serif body. Perfect for corporate and formal presentations.',
    author: 'System',
    primaryFont: ['Playfair Display', 'Georgia', 'serif'],
    secondaryFont: ['Inter', 'system-ui', 'sans-serif'],
    monoFont: ['JetBrains Mono', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.majorThird,
    googleFonts: ['Playfair+Display:400,400i,700,900', 'Inter:300,400,500,600,700'],
    category: 'serif',
    tags: ['professional', 'corporate', 'elegant', 'formal'],
    roles: {
      title: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 96,
        fontWeight: 900,
        lineHeight: 1.1,
        letterSpacing: -0.02,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 42,
        fontWeight: 300,
        lineHeight: 1.3,
        textAlign: 'center',
        letterSpacing: 0.02,
      },
      sectionHeader: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 72,
        fontWeight: 700,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 64,
        fontWeight: 700,
        lineHeight: 1.2,
      },
      heading2: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 48,
        fontWeight: 700,
        lineHeight: 1.3,
      },
      heading3: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 36,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bodyLarge: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.6,
      },
      bodySmall: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bullet: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 52,
        fontWeight: 400,
        fontStyle: 'italic',
        lineHeight: 1.4,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 500,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: 0.08,
      },
      footnote: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['JetBrains Mono', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Inter', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Playfair Display', 'Georgia', 'serif'],
        fontSize: 120,
        fontWeight: 900,
        textTransform: 'uppercase',
      },
    },
  },

  // 2. Modern Tech - Poppins + Roboto
  {
    id: 'modern-tech',
    name: 'Modern Tech',
    description: 'Clean, geometric sans-serif combination. Ideal for tech presentations and startups.',
    author: 'System',
    primaryFont: ['Poppins', 'system-ui', 'sans-serif'],
    secondaryFont: ['Roboto', 'system-ui', 'sans-serif'],
    monoFont: ['Fira Code', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.perfectFourth,
    googleFonts: ['Poppins:300,400,500,600,700,800', 'Roboto:300,400,500,700', 'Fira+Code:400,500'],
    category: 'sans-serif',
    tags: ['modern', 'tech', 'startup', 'clean', 'minimal'],
    roles: {
      title: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 92,
        fontWeight: 700,
        lineHeight: 1.1,
        letterSpacing: -0.01,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 44,
        fontWeight: 300,
        lineHeight: 1.3,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 68,
        fontWeight: 600,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 60,
        fontWeight: 600,
        lineHeight: 1.2,
      },
      heading2: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 46,
        fontWeight: 600,
        lineHeight: 1.3,
      },
      heading3: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.65,
      },
      bodyLarge: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.55,
      },
      bodySmall: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.65,
      },
      bullet: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.85,
      },
      quote: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 48,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.45,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 500,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      label: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: 0.1,
      },
      footnote: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Fira Code', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Poppins', 'system-ui', 'sans-serif'],
        fontSize: 110,
        fontWeight: 800,
        textTransform: 'uppercase',
      },
    },
  },

  // 3. Editorial Elegance - Merriweather + Lato
  {
    id: 'editorial-elegance',
    name: 'Editorial Elegance',
    description: 'Readable serif with humanist sans-serif. Great for content-heavy and educational presentations.',
    author: 'System',
    primaryFont: ['Merriweather', 'Georgia', 'serif'],
    secondaryFont: ['Lato', 'system-ui', 'sans-serif'],
    monoFont: ['Source Code Pro', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.majorThird,
    googleFonts: ['Merriweather:300,300i,400,400i,700,900', 'Lato:300,400,700,900', 'Source+Code+Pro:400,500'],
    category: 'serif',
    tags: ['editorial', 'readable', 'educational', 'content-heavy'],
    roles: {
      title: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 88,
        fontWeight: 900,
        lineHeight: 1.15,
        letterSpacing: -0.01,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 40,
        fontWeight: 300,
        lineHeight: 1.35,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 68,
        fontWeight: 700,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 58,
        fontWeight: 700,
        lineHeight: 1.25,
      },
      heading2: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 44,
        fontWeight: 700,
        lineHeight: 1.35,
      },
      heading3: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 700,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bodyLarge: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.65,
      },
      bodySmall: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bullet: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 46,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.5,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 400,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 17,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: 0.06,
      },
      footnote: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Source Code Pro', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Lato', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Merriweather', 'Georgia', 'serif'],
        fontSize: 110,
        fontWeight: 900,
        textTransform: 'uppercase',
      },
    },
  },

  // 4. Creative Bold - Bebas Neue + Open Sans
  {
    id: 'creative-bold',
    name: 'Creative Bold',
    description: 'Impactful display font with friendly body text. Perfect for creative and marketing presentations.',
    author: 'System',
    primaryFont: ['Bebas Neue', 'Impact', 'sans-serif'],
    secondaryFont: ['Open Sans', 'system-ui', 'sans-serif'],
    monoFont: ['JetBrains Mono', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.perfectFifth,
    googleFonts: ['Bebas+Neue', 'Open+Sans:300,400,600,700,800'],
    category: 'display',
    tags: ['creative', 'bold', 'marketing', 'impact', 'modern'],
    roles: {
      title: {
        fontFamily: ['Bebas Neue', 'Impact', 'sans-serif'],
        fontSize: 108,
        fontWeight: 400,
        lineHeight: 0.95,
        letterSpacing: 0.02,
        textAlign: 'center',
        textTransform: 'uppercase',
      },
      subtitle: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 42,
        fontWeight: 300,
        lineHeight: 1.3,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Bebas Neue', 'Impact', 'sans-serif'],
        fontSize: 84,
        fontWeight: 400,
        lineHeight: 1.0,
        textAlign: 'left',
        textTransform: 'uppercase',
      },
      heading1: {
        fontFamily: ['Bebas Neue', 'Impact', 'sans-serif'],
        fontSize: 72,
        fontWeight: 400,
        lineHeight: 1.1,
        textTransform: 'uppercase',
      },
      heading2: {
        fontFamily: ['Bebas Neue', 'Impact', 'sans-serif'],
        fontSize: 56,
        fontWeight: 400,
        lineHeight: 1.2,
        textTransform: 'uppercase',
      },
      heading3: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 36,
        fontWeight: 700,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bodyLarge: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.6,
      },
      bodySmall: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bullet: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 48,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.45,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 600,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 800,
        textTransform: 'uppercase',
        letterSpacing: 0.08,
      },
      footnote: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['JetBrains Mono', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 800,
      },
      pageNumber: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Open Sans', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Bebas Neue', 'Impact', 'sans-serif'],
        fontSize: 140,
        fontWeight: 400,
        textTransform: 'uppercase',
      },
    },
  },

  // 5. Sophisticated Minimal - Cormorant Garamond + Montserrat
  {
    id: 'sophisticated-minimal',
    name: 'Sophisticated Minimal',
    description: 'Refined serif with geometric sans-serif. Excellent for luxury, fashion, and design presentations.',
    author: 'System',
    primaryFont: ['Cormorant Garamond', 'Garamond', 'serif'],
    secondaryFont: ['Montserrat', 'system-ui', 'sans-serif'],
    monoFont: ['IBM Plex Mono', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.goldenRatio,
    googleFonts: ['Cormorant+Garamond:300,300i,400,400i,600,700', 'Montserrat:200,300,400,500,600,700', 'IBM+Plex+Mono:400,500'],
    category: 'serif',
    tags: ['sophisticated', 'minimal', 'luxury', 'fashion', 'design'],
    roles: {
      title: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 98,
        fontWeight: 300,
        lineHeight: 1.05,
        letterSpacing: -0.02,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 38,
        fontWeight: 200,
        lineHeight: 1.4,
        textAlign: 'center',
        letterSpacing: 0.05,
      },
      sectionHeader: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 74,
        fontWeight: 400,
        lineHeight: 1.15,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 62,
        fontWeight: 600,
        lineHeight: 1.2,
      },
      heading2: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 48,
        fontWeight: 600,
        lineHeight: 1.3,
      },
      heading3: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 300,
        lineHeight: 1.8,
      },
      bodyLarge: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 300,
        lineHeight: 1.7,
      },
      bodySmall: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 22,
        fontWeight: 300,
        lineHeight: 1.8,
      },
      bullet: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 300,
        lineHeight: 2.0,
      },
      quote: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 52,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.4,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.4,
        textAlign: 'center',
        letterSpacing: 0.02,
      },
      caption: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 300,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 15,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: 0.12,
      },
      footnote: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 15,
        fontWeight: 300,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['IBM Plex Mono', 'Consolas', 'monospace'],
        fontSize: 22,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 300,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 600,
      },
      pageNumber: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 300,
      },
      date: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 300,
      },
      footer: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 14,
        fontWeight: 300,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Montserrat', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Cormorant Garamond', 'Garamond', 'serif'],
        fontSize: 120,
        fontWeight: 700,
        textTransform: 'uppercase',
      },
    },
  },

  // 6. Academic Authority - Crimson Text + Source Sans Pro
  {
    id: 'academic-authority',
    name: 'Academic Authority',
    description: 'Traditional serif with clean sans-serif. Ideal for academic, research, and scientific presentations.',
    author: 'System',
    primaryFont: ['Crimson Text', 'Times New Roman', 'serif'],
    secondaryFont: ['Source Sans Pro', 'system-ui', 'sans-serif'],
    monoFont: ['Source Code Pro', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.majorThird,
    googleFonts: ['Crimson+Text:400,400i,600,700', 'Source+Sans+Pro:300,400,600,700', 'Source+Code+Pro:400,500'],
    category: 'serif',
    tags: ['academic', 'research', 'scientific', 'traditional', 'authoritative'],
    roles: {
      title: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 84,
        fontWeight: 700,
        lineHeight: 1.15,
        letterSpacing: -0.01,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 40,
        fontWeight: 400,
        lineHeight: 1.35,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 66,
        fontWeight: 600,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 56,
        fontWeight: 600,
        lineHeight: 1.25,
      },
      heading2: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 44,
        fontWeight: 600,
        lineHeight: 1.35,
      },
      heading3: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bodyLarge: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.6,
      },
      bodySmall: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bullet: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.85,
      },
      quote: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 44,
        fontWeight: 400,
        fontStyle: 'italic',
        lineHeight: 1.5,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 400,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 17,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: 0.05,
      },
      footnote: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Source Code Pro', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Source Sans Pro', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Crimson Text', 'Times New Roman', 'serif'],
        fontSize: 110,
        fontWeight: 700,
        textTransform: 'uppercase',
      },
    },
  },

  // 7. Friendly Approachable - Nunito + Raleway
  {
    id: 'friendly-approachable',
    name: 'Friendly Approachable',
    description: 'Rounded, warm fonts that feel welcoming. Perfect for educational and community presentations.',
    author: 'System',
    primaryFont: ['Nunito', 'system-ui', 'sans-serif'],
    secondaryFont: ['Raleway', 'system-ui', 'sans-serif'],
    monoFont: ['Fira Code', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.majorThird,
    googleFonts: ['Nunito:300,400,600,700,800', 'Raleway:300,400,500,600,700', 'Fira+Code:400,500'],
    category: 'sans-serif',
    tags: ['friendly', 'approachable', 'educational', 'community', 'warm'],
    roles: {
      title: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 90,
        fontWeight: 800,
        lineHeight: 1.1,
        letterSpacing: -0.01,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 42,
        fontWeight: 300,
        lineHeight: 1.35,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 70,
        fontWeight: 700,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 60,
        fontWeight: 700,
        lineHeight: 1.25,
      },
      heading2: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 46,
        fontWeight: 700,
        lineHeight: 1.35,
      },
      heading3: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bodyLarge: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.65,
      },
      bodySmall: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bullet: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 48,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.45,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 500,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 17,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: 0.06,
      },
      footnote: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Fira Code', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Raleway', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Nunito', 'system-ui', 'sans-serif'],
        fontSize: 110,
        fontWeight: 800,
        textTransform: 'uppercase',
      },
    },
  },

  // 8. Corporate Clean - Roboto Slab + Roboto
  {
    id: 'corporate-clean',
    name: 'Corporate Clean',
    description: 'Modern slab serif with matching sans-serif. Excellent for business and consulting presentations.',
    author: 'System',
    primaryFont: ['Roboto Slab', 'Georgia', 'serif'],
    secondaryFont: ['Roboto', 'system-ui', 'sans-serif'],
    monoFont: ['Roboto Mono', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.majorThird,
    googleFonts: ['Roboto+Slab:300,400,500,700', 'Roboto:300,400,500,700', 'Roboto+Mono:400,500'],
    category: 'serif',
    tags: ['corporate', 'business', 'consulting', 'modern', 'clean'],
    roles: {
      title: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 88,
        fontWeight: 700,
        lineHeight: 1.1,
        letterSpacing: -0.01,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 42,
        fontWeight: 300,
        lineHeight: 1.35,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 68,
        fontWeight: 500,
        lineHeight: 1.2,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 58,
        fontWeight: 500,
        lineHeight: 1.25,
      },
      heading2: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 44,
        fontWeight: 500,
        lineHeight: 1.35,
      },
      heading3: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bodyLarge: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.6,
      },
      bodySmall: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bullet: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.85,
      },
      quote: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 46,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.45,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 500,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 17,
        fontWeight: 500,
        textTransform: 'uppercase',
        letterSpacing: 0.05,
      },
      footnote: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Roboto Mono', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Roboto', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Roboto Slab', 'Georgia', 'serif'],
        fontSize: 110,
        fontWeight: 700,
        textTransform: 'uppercase',
      },
    },
  },

  // 9. Artistic Expression - Spectral + Work Sans
  {
    id: 'artistic-expression',
    name: 'Artistic Expression',
    description: 'Expressive serif with versatile sans-serif. Great for creative, design, and art presentations.',
    author: 'System',
    primaryFont: ['Spectral', 'Georgia', 'serif'],
    secondaryFont: ['Work Sans', 'system-ui', 'sans-serif'],
    monoFont: ['Space Mono', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.augmentedFourth,
    googleFonts: ['Spectral:300,300i,400,400i,600,700,800', 'Work+Sans:300,400,500,600,700', 'Space+Mono:400,700'],
    category: 'serif',
    tags: ['artistic', 'creative', 'design', 'expressive', 'unique'],
    roles: {
      title: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 94,
        fontWeight: 800,
        lineHeight: 1.08,
        letterSpacing: -0.015,
        textAlign: 'center',
      },
      subtitle: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 40,
        fontWeight: 300,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 72,
        fontWeight: 700,
        lineHeight: 1.15,
        textAlign: 'left',
      },
      heading1: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 60,
        fontWeight: 700,
        lineHeight: 1.2,
      },
      heading2: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 46,
        fontWeight: 600,
        lineHeight: 1.3,
      },
      heading3: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 34,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bodyLarge: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.65,
      },
      bodySmall: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.75,
      },
      bullet: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 50,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.4,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 500,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: 0.08,
      },
      footnote: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Space Mono', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 700,
      },
      pageNumber: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Work Sans', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 500,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Spectral', 'Georgia', 'serif'],
        fontSize: 115,
        fontWeight: 800,
        textTransform: 'uppercase',
      },
    },
  },

  // 10. Bold Statement - Oswald + Libre Franklin
  {
    id: 'bold-statement',
    name: 'Bold Statement',
    description: 'Condensed display font with balanced sans-serif. Perfect for impactful, energetic presentations.',
    author: 'System',
    primaryFont: ['Oswald', 'Impact', 'sans-serif'],
    secondaryFont: ['Libre Franklin', 'system-ui', 'sans-serif'],
    monoFont: ['Inconsolata', 'Consolas', 'monospace'],
    baseSize: 24,
    scaleRatio: TYPOGRAPHY_SCALES.perfectFifth,
    googleFonts: ['Oswald:300,400,500,600,700', 'Libre+Franklin:300,400,500,600,700,800', 'Inconsolata:400,500,700'],
    category: 'display',
    tags: ['bold', 'impactful', 'energetic', 'statement', 'dynamic'],
    roles: {
      title: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 102,
        fontWeight: 700,
        lineHeight: 1.0,
        letterSpacing: -0.01,
        textAlign: 'center',
        textTransform: 'uppercase',
      },
      subtitle: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 42,
        fontWeight: 300,
        lineHeight: 1.35,
        textAlign: 'center',
      },
      sectionHeader: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 78,
        fontWeight: 600,
        lineHeight: 1.1,
        textAlign: 'left',
        textTransform: 'uppercase',
      },
      heading1: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 66,
        fontWeight: 600,
        lineHeight: 1.15,
        textTransform: 'uppercase',
      },
      heading2: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 50,
        fontWeight: 500,
        lineHeight: 1.25,
      },
      heading3: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 36,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      body: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bodyLarge: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 32,
        fontWeight: 400,
        lineHeight: 1.6,
      },
      bodySmall: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.7,
      },
      bullet: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 30,
        fontWeight: 400,
        lineHeight: 1.9,
      },
      quote: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 48,
        fontWeight: 300,
        fontStyle: 'italic',
        lineHeight: 1.45,
        textAlign: 'center',
      },
      citation: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 26,
        fontWeight: 600,
        lineHeight: 1.4,
        textAlign: 'center',
      },
      caption: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 400,
        lineHeight: 1.4,
        fontStyle: 'italic',
      },
      label: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 17,
        fontWeight: 500,
        textTransform: 'uppercase',
        letterSpacing: 0.08,
      },
      footnote: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      code: {
        fontFamily: ['Inconsolata', 'Consolas', 'monospace'],
        fontSize: 24,
        fontWeight: 400,
        lineHeight: 1.5,
      },
      emphasis: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 400,
        fontStyle: 'italic',
      },
      strong: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 28,
        fontWeight: 800,
      },
      pageNumber: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      date: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 18,
        fontWeight: 400,
      },
      footer: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
      },
      header: {
        fontFamily: ['Libre Franklin', 'system-ui', 'sans-serif'],
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 1.4,
      },
      watermark: {
        fontFamily: ['Oswald', 'Impact', 'sans-serif'],
        fontSize: 130,
        fontWeight: 700,
        textTransform: 'uppercase',
      },
    },
  },
];

export function getTypographySetById(id: string): TypographySet | undefined {
  return typographySets.find(set => set.id === id);
}

export function getTypographySetsByCategory(category: string): TypographySet[] {
  return typographySets.filter(set => set.category === category);
}

export function getTypographySetsByTag(tag: string): TypographySet[] {
  return typographySets.filter(set => set.tags?.includes(tag));
}